### ISSUE TITLE
[CLOSE]I getting errors in visual studio and i have tried over 2h

### ISSUE THREAD

**Issue by SimplyLulle** [smefpw/Indigo#122]
Hello, I wonder why I get so many errors in visual studio. Do I have to have the newest version of it? Or if someone else has all the files in the visual studio that can send over them or something else because I would like to make it undetected!

EMAIL: **SimplyLulle@gmail.com**

Updating just now :: https://gyazo.com/c7c19d72df52f53c07a0ce7c655524a6

**Comment by SimplyLulle** [comment]
Now after a while I start getting enough when I do not come in a way! Would someone be able to send a copy of all their files to the visual studio

**Comment by Jeimy041** [comment]
Did you install the directx SDK and add the directories to the project?
