### ISSUE TITLE
i don't know how to make pull requests 

### ISSUE THREAD

**Issue by the-one-duck** [smefpw/Indigo#146]
now it's client instead for client_panorama I would make a pull request but uhh ^^

**Comment by codsec** [comment]
go here --> https://github.com/smefpw/smefs-Indigo-Remastered/pulls
![image](https://user-images.githubusercontent.com/44205014/85491177-75486280-b5a9-11ea-817f-1981a31ee843.png)

**Comment by codsec** [comment]
let me know, when you send these updates because I'm looking to download it
